# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_markov_profile <- function(X, nLevels, maxLength) {
    .Call(`_ordinalEditDistance_run_markov_profile`, X, nLevels, maxLength)
}

run_ordinalEditDistance <- function(X, appendCost, incrementCost, incrementPower) {
    .Call(`_ordinalEditDistance_run_ordinalEditDistance`, X, appendCost, incrementCost, incrementPower)
}

